---
- name: Debug Playbook
  hosts: firewalls
  connection: local
  tasks:
    - name: Create LLDP Profile
      paloaltonetworks.panos.panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name="localhost.localdomain"]/network/profiles/lldp-profile
        element: |
            <entry name="Generic LLDP Profile">
              <option-tlvs>
                <management-address>
                  <enabled>no</enabled>
                </management-address>
                <port-description>yes</port-description>
                <system-name>yes</system-name>
                <system-description>yes</system-description>
                <system-capabilities>yes</system-capabilities>
              </option-tlvs>
            </entry>
