---
mlag_ibgp_peering_vrfs:
  base_vlan: 3000

evpn_rt_type:
  # admin_subfield: < "leaf_asn" | "spine_asn" | "vni" | <0-65535> | <0-4294967295> | default -> "vni" >
  admin_subfield: vni

# DC1 Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    enable_mlag_ibgp_peering_vrfs: true
    vrfs:
      TENANT_A_CLIENT:
        vrf_vni: 10
        static_routes:
          - destination_address_prefix: 10.1.0.0/16
            gateway: 10.1.10.1
            nodes: ['swtch07', 'switch08']
        redistribute_static: true
        svis:
          110:
            name: 'PR01-CLIENT'
            tags: ['pod01']
            enabled: true
            ip_address_virtual: 10.1.110.254/24
          10:
            name: 'PR01-FW-INTERCO-CLIENT'
            tags: ['pod03']
            enabled: true
            ip_address_virtual: 10.1.10.2/30
            firewalls:
              - name: firewall-pod03
                is_aggregate_interface: true
                firewall_interface: ethernet1/1
                firewall_ip: 10.1.10.1/30

      TENANT_A_SERVER:
        vrf_vni: 11
        static_routes:
          - destination_address_prefix: 10.1.0.0/16
            gateway: 10.1.11.1
            nodes: ['swtch07', 'switch08']
        redistribute_static: true
        svis:
          111:
            name: 'PR01-SERVER'
            tags: ['pod02']
            enabled: true
            ip_address_virtual: 10.1.111.254/24
          11:
            name: 'PR01-FW-INTERCO-SERVER'
            tags: ['pod03']
            enabled: true
            ip_address_virtual: 10.1.11.2/30
            firewalls:
              - name: firewall-pod03
                is_aggregate_interface: true
                firewall_interface: ethernet1/1
                firewall_ip: 10.1.11.1/30