l2leaf:
  defaults:
    platform: "{{ lab_platform }}"
    loopback_ipv4_pool: 192.168.1.0/24
    loopback_ipv4_offset: 8
    uplink_interfaces: ['ethernet1', 'ethernet2']
    uplink_switch_interfaces: [ethernet5, ethernet5]
    uplink_ipv4_pool: 172.31.254.0/24
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    rack01:
      filter:
        tags: [ 'pod01', 'dc1' ]
      nodes:
        switch13:
          id: 13
          mgmt_ip: 10.73.254.13/24
          uplink_switches: ['switch03', 'switch04']
          mac_address: '50:01:00:0d:00:00'
    rack02:
      filter:
        tags: [ 'pod02', 'dc1' ]
      nodes:
        switch14:
          id: 14
          mgmt_ip: 10.73.254.14/24
          uplink_switches: ['switch05', 'switch06']
          mac_address: '50:01:00:0e:00:00'
    rack03:
      filter:
        tags: [ 'pod03', 'dc1' ]
      nodes:
        switch15:
          id: 15
          mgmt_ip: 10.73.254.15/24
          uplink_switches: ['switch07', 'switch08']
          mac_address: '50:01:00:0f:00:00'