---
- name: Check connectivity to EOS devices
  hosts: eos
  connection: local
  tasks:
    - name: 'Get facts from EOS devices'
      arista.eos.eos_facts:
        gather_subset: min
        gather_network_resources: all


- name: Check connectivity to PANOS devices
  hosts: panos
  connection: local
  tasks:
    - name: 'Get facts from PANOS devices'
      paloaltonetworks.panos.panos_facts:
        provider: '{{ provider }}'