---
- name: Configure PANOS devices
  hosts: panos
  connection: local
  vars:
    state: 'absent'
  tasks:

  - name: Include device intended structure configuration variables
    tags: [deploy]
    include_vars: "{{ filename }}"
    delegate_to: localhost
    vars:
      filename: "{{ structured_dir }}/{{ inventory_hostname }}.yml"

  - name: 'Remove Security Policies'
    paloaltonetworks.panos.panos_security_rule:
      provider: '{{ provider }}'
      rule_name: '{{item.rule_name}}'
      rule_type: '{{ item.rule_type }}'
      description: '{{ item.description }}'
      source_zone: '{{ item.source_zone }}'
      source_ip: '{{ item.source_ip }}'
      destination_zone: '{{ item.destination_zone}}'
      destination_ip: '{{ item.destination_ip }}'
      application: '{{ item.application }}'
      service: '{{ item.service | default(["application-default"]) }}'
      action: '{{ item.action }}'
      state: '{{ state }}'
    loop:
      '{{ security_policies }}'

  # - name: commit changes by specified admins to firewall
  #   tags: [polic, deploy]
  #   paloaltonetworks.panos.panos_commit_firewall:
  #     provider: '{{ provider }}'

  - name: 'Remove secutiry objects'
    paloaltonetworks.panos.panos_address_object:
      provider: '{{ provider }}'
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      description: '{{ item.description }}'
      state: "{{ state | default('present') }}"
    loop:
      '{{ security_objects }}'

  - name: 'Remove Static routes'
    paloaltonetworks.panos.panos_static_route:
      provider: '{{ provider }}'
      name: '{{ item.name | default(noname) }}'
      destination: '{{ item.destination }}'
      nexthop: '{{ item.nexthop }}'
      virtual_router: '{{ item.virtual_router }}'
      state: "{{ state | default('present') }}"
    loop:
      '{{ static_routes }}'

  - name: 'Remove L3 Subinterfaces'
    paloaltonetworks.panos.panos_l3_subinterface:
      provider: '{{ provider }}'
      name: "{{item.name}}"
      tag: '{{item.tag}}'
      enable_dhcp: false
      ip: '{{item.ip}}'
      zone_name: "{{item.zone_name}}"
      vr_name: "{{ item.virtual_router }}"
      state: "{{ state | default('present') }}"
    loop:
      '{{ l3_subinterfaces }}'

  - name: 'Remove Physical interfaces'
    paloaltonetworks.panos.panos_interface:
      provider: '{{ provider }}'
      if_name: "{{ item.if_name }}"
      enable_dhcp: false
      lldp_enabled: "{{ item.lldp_enabled | default(False) }}"
      lldp_profile: "{{ item.lldp_profile | default('') }}"
      mode: "{{ item.mode }}"
      state: "{{ state | default('present') }}"
    loop:
      "{{ interfaces }}"

  - name: 'Remove security zones'
    paloaltonetworks.panos.panos_zone:
      provider: '{{ provider }}'
      zone: '{{ item }}'
      mode: 'layer3'
      state: "{{ state | default('present') }}"
    loop:
      "{{ security_zones }}"

  - name: 'Remove Virtual Routers'
    paloaltonetworks.panos.panos_virtual_router:
      provider: '{{ provider }}'
      name: '{{ item }}'
      state: '{{ state }}'
    loop:
      "{{ virtual_routers }}"

  - name: 'Remove Interface Management profile'
    paloaltonetworks.panos.panos_management_profile:
      provider: '{{ provider }}'
      name: '{{ item.name }}'
      ping: '{{ item.ping }}'
      ssh: '{{ item.ssh }}'
      state: '{{ state }}'
    loop:
      "{{ management_profile }}"

  - name: commit changes by specified admins to firewall
    tags: [polic, deploy]
    paloaltonetworks.panos.panos_commit_firewall:
      provider: '{{ provider }}'