---
- name: Configure PANOS devices
  hosts: panos
  connection: local
  vars:
    state: 'present'
  tasks:
  - name: 'Generate strctured config for {{ inventory_hostname }}'
    tags: [build]
    include_role:
      name: avd_firewall_panos

  - name: Include device intended structure configuration variables
    tags: [deploy]
    include_vars: "{{ filename }}"
    delegate_to: localhost
    vars:
      filename: "{{ structured_dir }}/{{ inventory_hostname }}.yml"

  - name: Create LLDP Profile
    tags: [deploy]
    paloaltonetworks.panos.panos_type_cmd:
      provider: '{{ provider }}'
      xpath: |
        /config/devices/entry[@name="localhost.localdomain"]/network/profiles/lldp-profile
      element: |
          <entry name="standardlldp">
            <option-tlvs>
              <management-address>
                <enabled>no</enabled>
              </management-address>
              <port-description>yes</port-description>
              <system-name>yes</system-name>
              <system-description>yes</system-description>
              <system-capabilities>yes</system-capabilities>
            </option-tlvs>
          </entry>

  - name: 'Create Interface Management profile'
    tags: [deploy]
    paloaltonetworks.panos.panos_management_profile:
      provider: '{{ provider }}'
      name: '{{ item.name }}'
      ping: '{{ item.ping }}'
      ssh: '{{ item.ssh }}'
      state: '{{ state }}'
    loop:
      "{{ management_profile }}"

  - name: 'Create Virtual Routers'
    tags: [deploy]
    paloaltonetworks.panos.panos_virtual_router:
      provider: '{{ provider }}'
      name: '{{ item }}'
      state: '{{ state }}'
    loop:
      "{{ virtual_routers }}"

  - name: 'Create security zones'
    tags: [deploy]
    paloaltonetworks.panos.panos_zone:
      provider: '{{ provider }}'
      zone: '{{ item }}'
      mode: 'layer3'
      state: "{{ state | default('present') }}"
    loop:
      "{{ security_zones }}"

  - name: 'Configure Physical interfaces'
    tags: [deploy]
    paloaltonetworks.panos.panos_interface:
      provider: '{{ provider }}'
      if_name: "{{ item.if_name }}"
      enable_dhcp: false
      mode: "{{ item.mode }}"
      state: "{{ state | default('present') }}"
    loop:
      "{{ interfaces }}"

  - name: 'Configure L3 Subinterfaces'
    tags: [deploy]
    paloaltonetworks.panos.panos_l3_subinterface:
      provider: '{{ provider }}'
      name: "{{item.name}}"
      tag: '{{item.tag}}'
      enable_dhcp: false
      ip: '{{item.ip}}'
      zone_name: "{{item.zone_name}}"
      management_profile: '{{ item.management_profile }}'
      vr_name: "{{ item.virtual_router }}"
      state: "{{ state | default('present') }}"
      # Workaround from https://github.com/PaloAltoNetworks/pan-os-ansible/issues/238
      vsys: "vsys1"
    loop:
      '{{ l3_subinterfaces }}'

  - name: Create Static routes
    tags: [deploy]
    paloaltonetworks.panos.panos_static_route:
      provider: '{{ provider }}'
      name: '{{ item.name | default(noname) }}'
      destination: '{{ item.destination }}'
      nexthop: '{{ item.nexthop }}'
      virtual_router: '{{ item.virtual_router }}'
      state: "{{ state | default('present') }}"
    loop:
      '{{ static_routes }}'

  - name: Create object 'Test-One'
    tags: [deploy]
    paloaltonetworks.panos.panos_address_object:
      provider: '{{ provider }}'
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      description: '{{ item.description }}'
      state: "{{ state | default('present') }}"
    loop:
      '{{ security_objects }}'

  - name: Create Security Policies
    tags: [policy, never]
    paloaltonetworks.panos.panos_security_rule:
      provider: '{{ provider }}'
      rule_name: '{{item.rule_name}}'
      rule_type: '{{ item.rule_type }}'
      description: '{{ item.description }}'
      source_zone: '{{ item.source_zone }}'
      source_ip: '{{ item.source_ip }}'
      destination_zone: '{{ item.destination_zone}}'
      destination_ip: '{{ item.destination_ip }}'
      application: '{{ item.application | default(["any"]) }}'
      service: '{{ item.service | default(["any"]) }}'
      action: '{{ item.action }}'
    loop:
      '{{ security_policies }}'

  - name: commit changes by specified admins to firewall
    tags: [policy, deploy]
    paloaltonetworks.panos.panos_commit_firewall:
      provider: '{{ provider }}'